### ISSUE TITLE
PRACTICA #3 ARCHITEC

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-3-practica-architect-irvinjs22620075#1]
[REORTE DE RACTICA ARCHITEC.pdf](https://github.com/user-attachments/files/16843653/REORTE.DE.RACTICA.ARCHITEC.pdf)

Equipo:
Cruz Cruz Diego
Jimenez Sanchez Irvin
Rosas Garcia Marco Uriel
5BS

**Comment by Anakimberly** [comment]
Tienen el 20% cumple con todo lo que se menciona en la rubrica, esta muy bien estructurado.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
